workflows:
  ios_unsigned:
    name: iOS unsigned (CI bootstrap)
    max_build_duration: 60
    environment:
      vars:
        API_BASE_URL: "https://provokely.com"
        ENABLE_FCM: "false"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - | 
        flutter --version
        # Ensure iOS platform exists but keep committed Podfile (iOS 13.0)
        if [ ! -f ios/Runner.xcodeproj/project.pbxproj ]; then
          flutter create --platforms=ios .
        fi
        echo "--- iOS directory ---"
        ls -la ios || true
        ls -la ios/Runner.xcodeproj || true
        test -f ios/Runner.xcodeproj/project.pbxproj || (echo "xcodeproj missing" && exit 1)
        flutter pub get
        # Install CocoaPods with repo update so minimum target settings apply
        cd ios && pod install --repo-update && cd ..
        bash scripts/config_platforms.sh || true
        flutter build ipa --release --no-codesign \
          --dart-define=API_BASE_URL=$API_BASE_URL \
          --dart-define=ENABLE_FCM=$ENABLE_FCM
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - flutter_drive.log

  ios_simulator_debug:
    name: iOS Simulator Debug (no signing)
    max_build_duration: 60
    environment:
      vars:
        API_BASE_URL: "https://provokely.com"
        ENABLE_FCM: "false"
      flutter: stable
      xcode: latest
    scripts:
      - |
        flutter --version
        if [ ! -f ios/Runner.xcodeproj/project.pbxproj ]; then
          flutter create --platforms=ios .
        fi
        flutter pub get
        cd ios && pod install --repo-update && cd ..
        bash scripts/config_platforms.sh || true
        # Build for simulator to avoid signing; produces .app
        flutter build ios --simulator --debug \
          --dart-define=API_BASE_URL=$API_BASE_URL \
          --dart-define=ENABLE_FCM=$ENABLE_FCM
        # Zip the .app for artifact download
        APP_PATH=$(ls -d build/ios/iphonesimulator/*.app | head -n 1)
        (cd build/ios/iphonesimulator && zip -r app-simulator.zip "$(basename "$APP_PATH")")
    artifacts:
      - build/ios/iphonesimulator/app-simulator.zip

  android_debug:
    name: Android debug APK
    max_build_duration: 60
    environment:
      vars:
        API_BASE_URL: "https://provokely.com"
        ENABLE_FCM: "false"
      flutter: stable
    scripts:
      - |
        flutter --version
        # Ensure Android & iOS platforms exist (needed for some Flutter tooling)
        if [ ! -f android/app/build.gradle ]; then
          rm -rf android
          flutter create --platforms=android .
        fi
        if [ ! -f ios/Runner.xcodeproj/project.pbxproj ]; then
          rm -rf ios
          flutter create --platforms=ios .
        fi
        flutter pub get
        bash scripts/config_platforms.sh || true
        # Build minimized split-per-abi release APKs for smaller size
        flutter build apk --release --split-per-abi \
          --dart-define=API_BASE_URL=$API_BASE_URL \
          --dart-define=ENABLE_FCM=$ENABLE_FCM
    artifacts:
      - build/app/outputs/flutter-apk/*-release.apk


