name: provokely_app
description: Provokely MVP mobile app (Android & iOS)
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter_secure_storage: ^9.2.2
  go_router: ^14.2.7
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  url_launcher: ^6.3.0
  uni_links: ^0.5.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.0.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets: []


