name: Android Build (manual)

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Flutter pub get
        run: flutter pub get
      - name: Configure deep links
        run: bash scripts/config_platforms.sh || true
      - name: Build APK (debug)
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL || 'https://example.com' }}
        run: flutter build apk --debug --dart-define=API_BASE_URL=${API_BASE_URL}
      - name: Build AAB (release)
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL || 'https://example.com' }}
        run: flutter build appbundle --release --dart-define=API_BASE_URL=${API_BASE_URL}
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: provokely-apk-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: provokely-aab-release
          path: build/app/outputs/bundle/release/app-release.aab


